// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package dialect

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CloseDialect is the `closeDialect` instruction.
type CloseDialect struct {
	DialectNonce *uint8

	// [0] = [WRITE, SIGNER] owner
	//
	// [1] = [WRITE] dialect
	//
	// [2] = [] rent
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCloseDialectInstructionBuilder creates a new `CloseDialect` instruction builder.
func NewCloseDialectInstructionBuilder() *CloseDialect {
	nd := &CloseDialect{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetDialectNonce sets the "dialectNonce" parameter.
func (inst *CloseDialect) SetDialectNonce(dialectNonce uint8) *CloseDialect {
	inst.DialectNonce = &dialectNonce
	return inst
}

// SetOwnerAccount sets the "owner" account.
func (inst *CloseDialect) SetOwnerAccount(owner ag_solanago.PublicKey) *CloseDialect {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(owner).WRITE().SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *CloseDialect) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetDialectAccount sets the "dialect" account.
func (inst *CloseDialect) SetDialectAccount(dialect ag_solanago.PublicKey) *CloseDialect {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(dialect).WRITE()
	return inst
}

// GetDialectAccount gets the "dialect" account.
func (inst *CloseDialect) GetDialectAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetRentAccount sets the "rent" account.
func (inst *CloseDialect) SetRentAccount(rent ag_solanago.PublicKey) *CloseDialect {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *CloseDialect) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *CloseDialect) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CloseDialect {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *CloseDialect) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst CloseDialect) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CloseDialect,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CloseDialect) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CloseDialect) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.DialectNonce == nil {
			return errors.New("DialectNonce parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Owner is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Dialect is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Rent is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *CloseDialect) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CloseDialect")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("DialectNonce", *inst.DialectNonce))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("        owner", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      dialect", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("         rent", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj CloseDialect) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `DialectNonce` param:
	err = encoder.Encode(obj.DialectNonce)
	if err != nil {
		return err
	}
	return nil
}
func (obj *CloseDialect) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `DialectNonce`:
	err = decoder.Decode(&obj.DialectNonce)
	if err != nil {
		return err
	}
	return nil
}

// NewCloseDialectInstruction declares a new CloseDialect instruction with the provided parameters and accounts.
func NewCloseDialectInstruction(
	// Parameters:
	dialectNonce uint8,
	// Accounts:
	owner ag_solanago.PublicKey,
	dialect ag_solanago.PublicKey,
	rent ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *CloseDialect {
	return NewCloseDialectInstructionBuilder().
		SetDialectNonce(dialectNonce).
		SetOwnerAccount(owner).
		SetDialectAccount(dialect).
		SetRentAccount(rent).
		SetSystemProgramAccount(systemProgram)
}
