// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package dialect

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SubscribeUser is the `subscribeUser` instruction.
type SubscribeUser struct {
	DialectNonce  *uint8
	MetadataNonce *uint8

	// [0] = [WRITE, SIGNER] signer
	//
	// [1] = [] user
	//
	// [2] = [WRITE] metadata
	//
	// [3] = [] dialect
	//
	// [4] = [] rent
	//
	// [5] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSubscribeUserInstructionBuilder creates a new `SubscribeUser` instruction builder.
func NewSubscribeUserInstructionBuilder() *SubscribeUser {
	nd := &SubscribeUser{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetDialectNonce sets the "dialectNonce" parameter.
func (inst *SubscribeUser) SetDialectNonce(dialectNonce uint8) *SubscribeUser {
	inst.DialectNonce = &dialectNonce
	return inst
}

// SetMetadataNonce sets the "metadataNonce" parameter.
func (inst *SubscribeUser) SetMetadataNonce(metadataNonce uint8) *SubscribeUser {
	inst.MetadataNonce = &metadataNonce
	return inst
}

// SetSignerAccount sets the "signer" account.
func (inst *SubscribeUser) SetSignerAccount(signer ag_solanago.PublicKey) *SubscribeUser {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *SubscribeUser) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetUserAccount sets the "user" account.
func (inst *SubscribeUser) SetUserAccount(user ag_solanago.PublicKey) *SubscribeUser {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(user)
	return inst
}

// GetUserAccount gets the "user" account.
func (inst *SubscribeUser) GetUserAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetMetadataAccount sets the "metadata" account.
func (inst *SubscribeUser) SetMetadataAccount(metadata ag_solanago.PublicKey) *SubscribeUser {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(metadata).WRITE()
	return inst
}

// GetMetadataAccount gets the "metadata" account.
func (inst *SubscribeUser) GetMetadataAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetDialectAccount sets the "dialect" account.
func (inst *SubscribeUser) SetDialectAccount(dialect ag_solanago.PublicKey) *SubscribeUser {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(dialect)
	return inst
}

// GetDialectAccount gets the "dialect" account.
func (inst *SubscribeUser) GetDialectAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetRentAccount sets the "rent" account.
func (inst *SubscribeUser) SetRentAccount(rent ag_solanago.PublicKey) *SubscribeUser {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *SubscribeUser) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *SubscribeUser) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *SubscribeUser {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *SubscribeUser) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst SubscribeUser) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SubscribeUser,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SubscribeUser) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SubscribeUser) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.DialectNonce == nil {
			return errors.New("DialectNonce parameter is not set")
		}
		if inst.MetadataNonce == nil {
			return errors.New("MetadataNonce parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.User is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Metadata is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Dialect is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Rent is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *SubscribeUser) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SubscribeUser")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param(" DialectNonce", *inst.DialectNonce))
						paramsBranch.Child(ag_format.Param("MetadataNonce", *inst.MetadataNonce))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("       signer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("         user", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("     metadata", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("      dialect", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("         rent", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj SubscribeUser) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `DialectNonce` param:
	err = encoder.Encode(obj.DialectNonce)
	if err != nil {
		return err
	}
	// Serialize `MetadataNonce` param:
	err = encoder.Encode(obj.MetadataNonce)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SubscribeUser) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `DialectNonce`:
	err = decoder.Decode(&obj.DialectNonce)
	if err != nil {
		return err
	}
	// Deserialize `MetadataNonce`:
	err = decoder.Decode(&obj.MetadataNonce)
	if err != nil {
		return err
	}
	return nil
}

// NewSubscribeUserInstruction declares a new SubscribeUser instruction with the provided parameters and accounts.
func NewSubscribeUserInstruction(
	// Parameters:
	dialectNonce uint8,
	metadataNonce uint8,
	// Accounts:
	signer ag_solanago.PublicKey,
	user ag_solanago.PublicKey,
	metadata ag_solanago.PublicKey,
	dialect ag_solanago.PublicKey,
	rent ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *SubscribeUser {
	return NewSubscribeUserInstructionBuilder().
		SetDialectNonce(dialectNonce).
		SetMetadataNonce(metadataNonce).
		SetSignerAccount(signer).
		SetUserAccount(user).
		SetMetadataAccount(metadata).
		SetDialectAccount(dialect).
		SetRentAccount(rent).
		SetSystemProgramAccount(systemProgram)
}
